### ISSUE TITLE
Appet crasher, hvis man gemmer et waypoint uden at have udfyldt felterne

### ISSUE THREAD

**Issue by Spurux** [Spurux/MiniProjekt2#10]
Man får følgende fejlkode:
`04-30 10:35:53.015 19869-19869/dk.mahj.miniprojekt2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dk.mahj.miniprojekt2, PID: 19869
    java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1948)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
        at dk.mahj.miniprojekt2.WaypointEditActivity$4.onClick(WaypointEditActivity.java:177)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by Fire-Proof** [comment]
fixet i: #17
